version: "3.8"

services:
  db:
    image: ankane/pgvector
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - db-volume:/var/lib/postgresql/data

  app:
    build: .
    environment:
      - DB_HOST=db
    depends_on:
      - db
    ports:
      - 4000:4000

volumes:
  db-volume:
