version: "3.8"

services:
  api:
    build:
      context: .
      target: development
    volumes:
      - ./:/user/src/app
      - /user/src/app/node_modules
    ports:
      - 4000:4000
    depends_on:
      - db
    command: npm run dev

  db:
    image: postgres:14.5
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:${DB_PORT}"
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:
