version: "3.8"

services:
  api:
    build:
      context: .
      target: development
    volumes:
      - ./:/user/src/app
      - /user/src/app/node_modules
    ports:
      - 4000:4000
    depends_on:
      - db
    command: npm run dev

volumes:
  db-volume:
